name: Build and push Docker image

on:
  push:
    branches: [ master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_and_push:
    name: Build and push image to Docker Registry
    strategy:
      matrix:
        arch:
          - amd64
          - arm7
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Get info
        id: info
        run: |
          echo "::set-output name=repo::$(echo ${GITHUB_REPOSITORY#*/})"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.4.1
        id: buildx
        with:
          install: true
          driver: docker-container
          driver-opts: |
            image=moby/buildkit:master
            network=host

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3.7.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ matrix.arch == 'amd64' }}
            type=raw,priority=500,value=${{ matrix.arch }}-latest

      - name: Log in to the Container registry
        uses: docker/login-action@v1.14.1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.10.0
        with:
          context: .
          file: Dockerfile-${{ matrix.arch }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
